### ISSUE TITLE
acompany tag changed

### ISSUE THREAD

**Issue by RisingLeaf** [EricD112/Altera#17]
due to recent changes in the accompany tag, it is recommended to add the save tag to your npc. In `altera first contact.txt`

**Comment by EricD112** [comment]
Thanks for mentioning, save tag will be added with the next update. I'll leave the issue open until then.

**Comment by RisingLeaf** [comment]
> Thanks for mentioning, save tag will be added with the next update. I'll leave the issue open until then.

Nice

**Comment by EricD112** [comment]
I just pushed an update adding "save" to all cases of "accompany".
