### ISSUE TITLE
missing some definitions

### ISSUE THREAD

**Issue by Zavindur** [EricD112/Altera#7]
undefined outfits
outfitter "Ancient Advanced"
	"ADRX-I Draconic Reactor"#
	"ADRX-II Draconic Reactor"#
	"AMCX Module Converter"#
	"ASSX-I Shield System"#
	"ASSX-II Shield System"#

undefined ships
shipyard "Ancient Basic"
	"Aqueus"#

shipyard "Ancient Advanced"
	"Arqueus"#

**Comment by Zavindur** [comment]
btw, this mod looks amazing, the look of the ships feels very consistent but varied; looks like it's being done right, look forward to more content when available

**Comment by EricD112** [comment]
Thanks for reporting those errors. It seems I forgot to rename the module converter in the sales.txt and I ended up accidentally adding the Arqueus to the shipyards already, even though it doesn't exist yet. I've fixed the earlier, but I'll leave the Arqueus in, as it's gonna be in either the next update, or the one after.

**Comment by EricD112** [comment]
Issue should be resolved now.
